### ISSUE TITLE
clang: error: no such file or directory: '[1]'

### ISSUE THREAD

**Issue by HenrikEckermann** [stan-dev/rstan#827]
I had a working installation of rstan, which must have been <=2.21.1. I wanted to update another package so I can use cmdstanr. So I deleted the current rstan. Then deleted the StanHeaders. Restarted Rstudio and then wanted to install the newest rstan. Then I run into the error below. I also tried installing 2.21.1 instead of 2.21.2 but that gives the same error.

I run rstan on OS Catalina.

```
Downloading package from url: http://cran.us.r-project.org/src/contrib/Archive/rstan/rstan_2.21.1.tar.gz
Skipping 1 packages ahead of CRAN: Rcpp
[1] "hello, here is R"
* installing *source* package ‘rstan’ ...
** package ‘rstan’ successfully unpacked and MD5 sums checked
** using staged installation
** libs
clang++ -mmacosx-version-min=10.13 -std=gnu++14 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG -I"../inst/include" -I"../inst/include/boost_not_in_BH" -I"." -DBOOST_DISABLE_ASSERTS -DBOOST_PHOENIX_NO_VARIADIC_EXPRESSION -DBOOST_NO_AUTO_PTR -D_REENTRANT -DSTAN_THREADS  [1] "hello, here is R" -I'/Library/Frameworks/R.framework/Versions/4.0/Resources/library/Rcpp/include' -I'/Library/Frameworks/R.framework/Versions/4.0/Resources/library/RcppEigen/include' -I'/Library/Frameworks/R.framework/Versions/4.0/Resources/library/BH/include' -I'/Library/Frameworks/R.framework/Versions/4.0/Resources/library/StanHeaders/include' -I'/Library/Frameworks/R.framework/Versions/4.0/Resources/library/RcppParallel/include' -I/usr/local/include   -fPIC  -Wall -g -O2  -c Module.cpp -o Module.o
clang: error: no such file or directory: '[1]'
clang: error: no such file or directory: 'hello, here is R'
make: *** [Module.o] Error 1
ERROR: compilation failed for package ‘rstan’
```

EDIT:
Deleting StanHeaders and the choosing "no" when it asks to install from source allowed me to install 2.21.1 again. I still cannot install 2.21.2 though.

**Comment by jgabry** [comment]
Sorry you're getting an error. Does it work to install RStan from GitHub? For that I recommend: 

```r
# remove old rstan
# restart R
# then run: 

remotes::install_github("stan-dev/rstan", ref = "develop", subdir = "rstan/rstan")
```

**Comment by HenrikEckermann** [comment]
Hi Jonah,

Thanks for your support. I tried that already yesterday. That did not work. Just so you know: It is not pressuring for me to install 2.21.2 now that I can work with 2.21.1. Let me know if you want me to try something else!

**Comment by jgabry** [comment]
Hmmm, I'm not sure what's going here. @bgoodri any ideas for what else @HenrikEckermann can try to get this working?

**Comment by bgoodri** [comment]
The

[1] "hello, here is R"

thing messes everything up. I imagine that it comes from a .Rprofile file
or something like that..

**Comment by HenrikEckermann** [comment]
Indeed after deleting the rProfile file it worked...

**Comment by jgabry** [comment]
Great, glad that works. Good catch @bgoodri.

**Comment by bgoodri** [comment]
You wouldn't have needed to delete the .Rprofile file entirely; just the
line(s) in it that print text.
