### ISSUE TITLE
Can't C++ compile valid Stan program. "error: call to 'sqrt' is ambiguous"

### ISSUE THREAD

**Issue by syclik** [stan-dev/rstan#506]
#### Summary:
Error in compiling a valid Stan program. 

This was reported as stan-dev/stan#2478. I believe this is an RStan issue, not a Stan issue.

I had originally thought it was a C++ compiler bug, but I can recreate it on my Mac. It compiles fine with CmdStan.

#### Description:
A valid Stan program compiles in CmdStan v2.17.1, but does not compile in RStan 2.17.3.

#### Reproducible Steps:

This should work, but doesn't compile in RStan. 
```stan
transformed data {
  real one = sqrt(1);
}
parameters {
  real theta;
}
model {
  theta ~ normal(0, 1);
}
```

#### Current Output:

Some abbreviation for clarity:

```
> fit <- stan("issue.stan")
In file included from file83070aa99a6.cpp:8:
...
#  define BOOST_NO_CXX11_RVALUE_REFERENCES
          ^
<command line>:6:9: note: previous definition is here
#define BOOST_NO_CXX11_RVALUE_REFERENCES 1
        ^
file83070aa99a6.cpp:77:36: error: call to 'sqrt' is ambiguous
            stan::math::assign(one,sqrt(1));
                                   ^~~~
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/math.h:970:1: note: candidate function [with _A1 = int]
sqrt(_A1 __lcpp_x) _NOEXCEPT {return ::sqrt((double)__lcpp_x);}
^
/Library/Frameworks/R.framework/Versions/3.4/Resources/library/StanHeaders/include/stan/math/prim/mat/fun/sqrt.hpp:32:5: note: candidate function [with T = int]
    sqrt(const T& x) {
    ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/usr/include/math.h:447:15: note: candidate function
extern double sqrt(double);
              ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/math.h:963:46: note: candidate function
inline _LIBCPP_INLINE_VISIBILITY float       sqrt(float __lcpp_x) _NOEXCEPT       {return ::sqrtf(__lcpp_x);}
                                             ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/math.h:964:46: note: candidate function
inline _LIBCPP_INLINE_VISIBILITY long double sqrt(long double __lcpp_x) _NOEXCEPT {return ::sqrtl(__lcpp_x);}
                                             ^
/Library/Frameworks/R.framework/Versions/3.4/Resources/library/StanHeaders/include/stan/math/rev/scal/fun/sqrt.hpp:50:16: note: candidate function
    inline var sqrt(const var& a) {
               ^
1 warning and 1 error generated.
make: *** [file83070aa99a6.o] Error 1

ERROR(s) during compilation: source code errors or compiler configuration errors!

Program source:
  1: 
  2: // includes from the plugin
...
362: // definition
363: 
364: SEXP file83070aa99a6(  ){
365:  return Rcpp::wrap("issue");
366: }
367: 
368: 
Error in compileCode(f, code, language = language, verbose = verbose) : 
  Compilation ERROR, function(s)/method(s) not created! In file included from file83070aa99a6.cpp:8:
...
In addition: Warning message:
running command '/Library/Frameworks/R.framework/Resources/bin/R CMD SHLIB file83070aa99a6.cpp 2> file83070aa99a6.cpp.err.txt' had status 1 
```

#### Expected Output:
No error.

#### RStan Version:
```
> packageVersion("rstan")
[1] ‘2.17.3’
```

#### R Version:
```
> R.version.string
[1] "R version 3.4.0 (2017-04-21)"
```

#### Operating System:
Mac OS X 10.13.3

**Comment by syclik** [comment]
cc: @bgoodri, @bob-carpenter

**Comment by bgoodri** [comment]
https://github.com/stan-dev/stan/issues/2478#issuecomment-369350799

**Comment by syclik** [comment]
I'm not sure I understand what's going on. Is there some code that's in RStan (that's not in Stan) possibly bringing in another definition of `sqrt()` and other definitions of functions in the `std` namespace? 

If so, is there a way to remove that from RStan so we fix the problem generally? If not, do you know what other functions we need to implement within the math library to cover all uses?

Also, how do we test for that in the Math library? Is there an open Math issue that you can link? Perhaps we should keep this open until the Math library is fixed.

**Comment by bgoodri** [comment]
It never was a RStan issue. As I said in the link, it happens with a v2.17.x vintage of CmdStan. To repeat myself:
```
goodrich@T540p:/opt/cmdstan$ make /tmp/sqrt

--- Translating Stan model to C++ code ---
bin/stanc  /tmp/sqrt.stan --o=/tmp/sqrt.hpp
Model name=sqrt_model
Input file=/tmp/sqrt.stan
Output file=/tmp/sqrt.hpp

--- Linking C++ model ---
g++-7 -Wall -I . -isystem stan/lib/stan_math/lib/eigen_3.3.3 -isystem stan/lib/stan_math/lib/boost_1.64.0 -isystem stan/lib/stan_math/lib/cvodes_2.9.0/include -std=c++1y -DBOOST_RESULT_OF_USE_TR1 -DBOOST_NO_DECLTYPE -DBOOST_DISABLE_ASSERTS -DBOOST_PHOENIX_NO_VARIADIC_EXPRESSION -I src -I stan/src -isystem stan/lib/stan_math/ -DEIGEN_NO_DEBUG -DFUSION_MAX_VECTOR_SIZE=12 -DNO_FPRINTF_OUTPUT -pipe -lpthread  -O3 -o /tmp/sqrt src/cmdstan/main.cpp -include /tmp/sqrt.hpp stan/lib/stan_math/lib/cvodes_2.9.0/lib/libsundials_nvecserial.a stan/lib/stan_math/lib/cvodes_2.9.0/lib/libsundials_cvodes.a
In file included from <command-line>:0:0:
/tmp/sqrt.hpp: In member function ‘void sqrt_model_namespace::sqrt_model::ctor_body(stan::io::var_context&, unsigned int, std::ostream*)’:
/tmp/sqrt.hpp:125:240: error: call of overloaded ‘sqrt(int)’ is ambiguous
 :model::rvalue(qr_Q(x), stan::model::cons_list(stan::model::index_omni(), stan::model::cons_list(stan::model::index_min_max(1, K), stan::model::nil_index_list())), "qr_Q(x)"),sqrt((N - 1))));
                                                                                                                                                                                            ^
In file included from /usr/include/features.h:419:0,
                 from /usr/include/x86_64-linux-gnu/bits/libc-header-start.h:33,
                 from /usr/include/stdint.h:26,
                 from /usr/lib/gcc/x86_64-linux-gnu/7/include/stdint.h:9,
                 from stan/lib/stan_math/stan/math/memory/stack_alloc.hpp:6,
                 from stan/lib/stan_math/stan/math/rev/core/autodiffstackstorage.hpp:4,
                 from stan/lib/stan_math/stan/math/rev/core.hpp:4,
                 from stan/lib/stan_math/stan/math/rev/mat.hpp:4,
                 from stan/lib/stan_math/stan/math.hpp:4,
                 from stan/src/stan/model/model_header.hpp:4,
                 from /tmp/sqrt.hpp:3,
                 from <command-line>:0:
/usr/include/x86_64-linux-gnu/bits/mathcalls.h:149:1: note: candidate: double sqrt(double)
 __MATHCALL (sqrt,, (_Mdouble_ __x));
 ^
In file included from stan/lib/stan_math/lib/boost_1.64.0/boost/config/no_tr1/cmath.hpp:21:0,
                 from stan/lib/stan_math/lib/boost_1.64.0/boost/math/tools/config.hpp:19,
                 from stan/lib/stan_math/stan/math/rev/core/var.hpp:7,
                 from stan/lib/stan_math/stan/math/rev/core/gevv_vvv_vari.hpp:5,
                 from stan/lib/stan_math/stan/math/rev/core.hpp:12,
                 from stan/lib/stan_math/stan/math/rev/mat.hpp:4,
                 from stan/lib/stan_math/stan/math.hpp:4,
                 from stan/src/stan/model/model_header.hpp:4,
                 from /tmp/sqrt.hpp:3,
                 from <command-line>:0:
/usr/include/c++/7/cmath:463:3: note: candidate: constexpr float std::sqrt(float)
   sqrt(float __x)
   ^~~~
/usr/include/c++/7/cmath:467:3: note: candidate: constexpr long double std::sqrt(long double)
   sqrt(long double __x)
   ^~~~
/usr/include/c++/7/cmath:475:5: note: candidate: constexpr typename __gnu_cxx::__enable_if<std::__is_integer<_Tp>::__value, double>::__type std::sqrt(_Tp) [with _Tp = int; typename __gnu_cxx::__enable_if<std::__is_integer<_Tp>::__value, double>::__type = double]
     sqrt(_Tp __x)
     ^~~~
In file included from stan/lib/stan_math/stan/math/rev/scal/fun/pow.hpp:5:0,
                 from stan/lib/stan_math/stan/math/rev/scal/fun/inc_beta.hpp:7,
                 from stan/lib/stan_math/stan/math/rev/scal/fun/grad_inc_beta.hpp:12,
                 from stan/lib/stan_math/stan/math/rev/scal.hpp:50,
                 from stan/lib/stan_math/stan/math/rev/arr.hpp:9,
                 from stan/lib/stan_math/stan/math/rev/mat.hpp:13,
                 from stan/lib/stan_math/stan/math.hpp:4,
                 from stan/src/stan/model/model_header.hpp:4,
                 from /tmp/sqrt.hpp:3,
                 from <command-line>:0:
stan/lib/stan_math/stan/math/rev/scal/fun/sqrt.hpp:50:16: note: candidate: stan::math::var stan::math::sqrt(const stan::math::var&)
     inline var sqrt(const var& a) {
                ^~~~
In file included from stan/lib/stan_math/stan/math/prim/mat.hpp:209:0,
                 from stan/lib/stan_math/stan/math/rev/mat.hpp:12,
                 from stan/lib/stan_math/stan/math.hpp:4,
                 from stan/src/stan/model/model_header.hpp:4,
                 from /tmp/sqrt.hpp:3,
                 from <command-line>:0:
stan/lib/stan_math/stan/math/prim/mat/fun/sqrt.hpp:32:5: note: candidate: typename stan::math::apply_scalar_unary<stan::math::sqrt_fun, T>::return_t stan::math::sqrt(const T&) [with T = int; typename stan::math::apply_scalar_unary<stan::math::sqrt_fun, T>::return_t = double]
     sqrt(const T& x) {
     ^~~~
make: *** [make/models:12: /tmp/sqrt] Error 1
```
But with the develop branch of CmdStan, it does not occur because the develop version of `stanc` is generating
```
goodrich@T540p:/tmp$ grep -F "sqrt(1)" sqrt.hpp
            stan::math::assign(one,stan::math::sqrt(1));
```
whereas the v2.17.x version of `stanc` was generating
```
goodrich@T540p:/tmp$ grep -F "sqrt(1)" sqrt_broken.hpp
            stan::math::assign(one,sqrt(1));
```

**Comment by maverickg** [comment]
I took a look, but could not figure out why so far.

**Comment by syclik** [comment]
@bgoodri, I'm using the tarball release of CmdStan v2.17.1. It's not even a
git clone. That compiles this just fine.

I'm going to check the generated code at v2.17.0 to see if that has the
unqualified version.

**Comment by syclik** [comment]
@bgoodri, just verified that this is a problem with CmdStan v2.17.0, which would mean that it's a problem with Stan v2.17.0.

So... how does the versioning work? I'm looking at the CRAN documentation for RStan 2.17.3 and it says it depends on StanHeaders 2.17.2. What version of Stan is packaged inside StanHeaders 2.17.2? Is it Stan v2.17.0?

**Comment by bgoodri** [comment]
StanHeaders 2.17.2 is released off the orphan branch that @seantalts made
from 2.17.0

**Comment by syclik** [comment]
Is that not Stan v2.17.1? I believe that's generating it with the fully qualified namespace.

I'll report back whether the orphan branch generates the code appropriately.

**Comment by bgoodri** [comment]
The orphaned branch branches off 2.17.0 and has a commit or two to fix the
char* vs. string slowdown.

**Comment by syclik** [comment]
Ok. I have no idea what commit that is, but I just verified that Stan v2.17.1 generates `stan::math::sqrt`.

Are there any other functions that we know that will also not compile using RStan? Are there any plans to fix RStan for v2.17.x?

**Comment by bgoodri** [comment]
I can't bump StanHeaders 2.17.1 without requiring C++14 on a point release.

**Comment by syclik** [comment]
Boo. Ok. Makes sense.

Damn... so somewhere between v2.17.0 and v2.17.1 we legitimately included C++14? And it's not just in the tests?

**Comment by bgoodri** [comment]
Yes, that was the reason for the orphan branch in the first place.

**Comment by syclik** [comment]
Got it. Thanks for walking me through the issue and the nuances of why it's this way. Feel free to lock the topic (I won't be commenting more unless you have questions for me).

**Comment by bob-carpenter** [comment]
We decided to only use as much of C++14 as was supported by one of the latest RTools C++ distributions.  If we included more than that, it's an error.

**Comment by bob-carpenter** [comment]
I just confirmed this is an issue with the develop branch of stan-dev/stan without R involved.

So we need to fix this in Stan itself ASAP.

**Comment by bob-carpenter** [comment]
Oops, meant to reopen the one in the Stan repo, not the RStan repo.

**Comment by seantalts** [comment]
We could fix 2.17.1 and make a 2.17.2 from it, no?

**Comment by bob-carpenter** [comment]
At some point, we just have to stop supporting pre-C++11.  

I don't want to continually have to patch 2.17.x versions as we move forward.

**Comment by seantalts** [comment]
Agreed. I don't feel strongly about this particular thing. I do feel strongly about making sure if we're doing extra work, that someone actually needs it (i.e. making sure someone needs this bugfix and can't run gcc before 4.9.3).

**Comment by bob-carpenter** [comment]
Unless someone tells us they need it, it's hard to tell who'd use pre-C++11.  My guess is that if we provide C++11 as our current stable version, that those who can't use C++11 will just find a different tool rather than writing to us in the hope that we can support pre-C++11.    Whereas if we continue to support pre-C++11, we'll pick those users up.  I think it's hard to tell what that's worth to us.  I'd rather just wait.  I'm happy piling up hacks and bug lists in pre-C++11 Stan.

Most packages I see coming out now depend on C++11.

**Comment by bgoodri** [comment]
This is only tangentially a C++11 issue (and not a very important one given
that the user has an easy workaround). It seems that C++11 compatible
compilers tend to put functions like sqrt into cmath that lead to the
ambiguity, irrespective of what -std is set to. The problem will likely go
away in the next Stan release because stanc is now generating calls to
stan::math::sqrt(1) --- which has a specialization for int --- instead of
sqrt(1) --- which could take 1 to be int, float, double, long double, etc.

In fact, the problem already has gone away in CmdStan 2.17.1 because that
is based on Stan 2.17.1, which generates stan::math::sqrt(1). But 2.17.1
had 200 commits over 2.17.0, some of which introduced syntax that is
specific to C++11, in anticipation that 2.18.0 would follow 2.17.0. But
2.17.0 was much slower due to the string vs. char* thing, so we had to fix
that with a commit or two. Sean didn't want to merge those two commits into
master (which was then at the same state as 2.17.0) because of some fear
that there would be merge conflicts when we updated master to 2.18.0.

Instead, Sean made a branch off the v2.17.0 that had a couple of commits,
which I used for the current StanHeaders because using 2.17.1 would require
C++11 and break (without advance warning) a lot of R packages like rstanarm
that come with pre-generated / pre-compiled C++ code. So, it is really more
of an issue of bad development practice than about C++11 specifically. Bad
to not catch the char* vs. string slowdown before 2.17.0 was released, bad
that our git history is completely unbisectable, bad to not follow the
gitflow paradigm that we ostensibly adopted which would allow us to merge
critical bugfixes into master and immediately make a point release, bad to
worry about future merge conflicts when we had a more pressing concern in
the present, and bad to foist the C++11/14 requirement on downstream
without warning (AFAIK, we *still* have not announced that 2.18.0 will
require a compiler with adequate C++14 support).

**Comment by seantalts** [comment]
Stan 2.17.1 is using Stan Math 2.17.1. Stan Math 2.17.1 is the same as 2.17.0 except that it has the performance bugs fixed. Stan 2.17.1 does have other commits to the Stan repo in it, but I thought we weren't using C++11 in there yet? If we actually were, then I should have made a release with just the math bump. I could go back and make a 2.17.0.1 (or whatever we want to number it) with just Stan Math repo bugfixes different up and down the repos. (more stuff that would be easier with a single repo).

> AFAIK, we *still* have not announced that 2.18.0 will require a compiler with adequate C++14 support).

What kind of announcement would you like to see? If you search discourse for c++11 there are a few threads announcing this (like "C++11 is here!").

> bad to worry about future merge conflicts when we had a more pressing concern in the present

I'm not sure how this affected anything negatively, other than that our disagreement on this issue drew out the process of making a 2.17.1 release.

> bad to not follow the gitflow paradigm that we ostensibly adopted which would allow us to merge critical bugfixes into master and immediately make a point release

The gitflow thing was retroactive; no one said anything about a special point release for just that bug fix for any reason until after I made the bugfix and committed it to develop. The bug was in discussion for literally months before I saw it and took a crack at it.

**Comment by bgoodri** [comment]
We decided to follow the gitflow paradigm in 2013, but never actually
followed it. People just branched off develop regardless of whether they
were adding a feature, fixing a non-critical bug, or fixing a critical bug.
Also, we haven't really done release branches.

**Comment by seantalts** [comment]
Sorry, I said that wrong. I meant that we hadn't decided to make a hotfix for the bug until after the fix went into develop. I wasn't around for the gitflow thing.

I made a better announcement in General on Discourse in language that's more what I think users will care about here: http://discourse.mc-stan.org/t/bumping-supported-compiler-versions-for-stan-2-18/3558
Please feel free to edit the post or chime in if I missed anything.

Let me know if we want a 2.17.0-1 or whatever we'd like to call it with JUST the bugfix and no other diffs vs 2.17.0.

**Comment by bgoodri** [comment]
I don't think we need to do anything for this sqrt specialization ambiguity
issue; it is easily worked around. I do think we should be branching off
master to fix critical bugs like the char* vs string thing and releasing as
soon as the hotfix branch is merged.

**Comment by seantalts** [comment]
How do we know if a bug is critical?

**Comment by bgoodri** [comment]
It is basically a question of whether we would want to immediately do a
release. But presumably we would decide on that when the bug is discovered
and before it is fixed.

**Comment by bob-carpenter** [comment]
Not sure what you mean about worrying about future merge conflicts.

We haven't officially announced 2.18 at all.  I had thought during the meetings that Ben said it'd be OK for the R users to require C++11.  Did I misunderstand or did the situation change?

P.S.  I was wrong in my previous comment.  I actually can compile sqrt(1)---just can't assign the result to an int.

**Comment by bgoodri** [comment]
R users are basically fine; R developers need advance notice that their
downstream packages will break.

**Comment by bob-carpenter** [comment]
How do we deliver that advance notice?   I'm hoping MPI lands soon and we can release 2.18 in the next month or so.  If not, we should probably think of rolling what we have in 2.18 out anyway.  I have two concerns about infrequent releases---people will think we've stopped or hit a road block and people who contribute patches, features, etc., won't see them until a release.  For instance, Matthijs wrote foreach loops and they're just waiting for 2.18.

**Comment by bgoodri** [comment]
Basically, I have to email R package maintainers directly; not all of them
are guaranteed to read Discourse. If MPI will take another month, then
perhaps we do 2.18 without it, but if MPI will only take a couple of weeks,
then having to wait a couple of more weeks to get it to most people will
not be a great experience either.

**Comment by bob-carpenter** [comment]
At this point, I think MPI is just waiting on the build mechanics.  It shouldn't really touch R at all.  I wouldn't want to bet it'll be done in two weeks.  The consensus at the meeting seemed to be that we should wait for a bigger feature than what's currently in develop beyond 2.17.  

I don't think waiting two weeks will be a big deal.  We should know before everything lands when it's close to being ready.
